### ISSUE TITLE
rbfeeder on x64 - core dump

### ISSUE THREAD

**Issue by dlasher** [sdr-enthusiasts/docker-radarbox#166] opened 2023-03-15 22:57 UTC
proxmox 7.3 on AMD CPU in Ubuntu 22LTS KVM VM:

```
root@rbfeeder:/usr/bin# ./rbfeeder
[2023-03-15 15:55:04]  Starting RBFeeder Version 1.0.8 (build 20220708190411)
[2023-03-15 15:55:04]  Using configuration file: /etc/rbfeeder.ini
[2023-03-15 15:55:04]  Network-mode enabled.
[2023-03-15 15:55:04]  		Remote host to fetch data: 172.18.0.7
[2023-03-15 15:55:04]  		Remote port: 30005
[2023-03-15 15:55:04]  		Remote protocol: BEAST
[2023-03-15 15:55:04]  Using GNSS (when available)
[2023-03-15 15:55:04]  Start date/time: 2023-03-15 15:55:04
[2023-03-15 15:55:04]  Socket for ANRB created. Waiting for connections on port 32088
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
./rbfeeder: line 17:  3940 Segmentation fault      (core dumped) qemu-arm-static /usr/bin/rbfeeder_armhf "$@"

```

Known issue or more informaiton needed?

**Comment by mikenye** [comment] 2023-03-24 01:58
Can you try the i386 version? `ghcr.io/sdr-enthusiasts/docker-radarbox:latest_linux_i386`

**Comment by mikenye** [comment] 2023-03-30 04:57
Can you please give me your CPU type?

Run these commands on your host:

`cat /proc/cpuinfo`
`lscpu`

Thanks.

**Comment by mikenye** [comment] 2023-03-30 04:58
You could also try replacing the `image:` directive for this container with:

```yaml
build: https://github.com/sdr-enthusiasts/docker-radarbox.git#main
```

And then attempt to build the container yourself with `docker compose build rbfeeder`.

**Comment by luciodaou** [comment] 2023-04-28 01:59
I'm having the same issue.

According to https://gitlab.com/qemu-project/qemu/-/issues/1079 this could be solved updating qemu to version 7.0. Radarbox image currently uses qemu 5.2.

**Comment by kr105** [comment] 2023-04-30 01:01
I had the same issue, after some trial and error I found this and that fixed the issue:

https://github.com/sdr-enthusiasts/docker-radarbox/blob/main/version_0.4.3_workarounds.md#workaround-for-temperature-sensor

**Comment by luciodaou** [comment] 2023-04-30 18:24
Thanks, @kr105 , now I remember there used to be this fix on the previous version of the guide.

Everything worked out fine, finally. I'm editing my previous post.

**Comment by kx1t** [comment] 2023-11-21 13:45
Looks like the issue is solved; closing.

Note -- as per Nov 20, 2023, Airnav made (yet another breaking) change to their `rbfeeder` software. If you are using our containers on any x86 platform that doesn't have a "Serial    : xxxx" entry in `/proc/cpuinfo` (which is: almost every x86 Linux installation we've come across), you MUST follow these instructions to make it work: https://github.com/sdr-enthusiasts/docker-radarbox/blob/main/version_0.4.3_workarounds.md#workaround-for-cpu-serial

**Closed by kx1t** 2023-11-21 13:45 UTC
